[package]
name = "barforge-types"
version = "0.0.1"
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true

[dev-dependencies]
jsonschema = "0.38.1"
serde_json.workspace = true
serde_yml.workspace = true
